spring:
  http:
    encoding:
      charset: UTF-8
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/malldb?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&autoReconnection=true
    username: ####
    password: ####
    

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8082
     